// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQH0igY5atcI7OaPbdBsJTUr_egpW5b1Q',
    appId: '1:93113263271:web:c73f1103730bd0891aa782',
    messagingSenderId: '93113263271',
    projectId: 'life-way-2003',
    authDomain: 'life-way-2003.firebaseapp.com',
    storageBucket: 'life-way-2003.appspot.com',
    measurementId: 'G-6RX0DG95RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcD6QXuif5jtz4sb0xgaA86Y17j3b-7xw',
    appId: '1:93113263271:android:4492c2c860a054971aa782',
    messagingSenderId: '93113263271',
    projectId: 'life-way-2003',
    storageBucket: 'life-way-2003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbIoQFq1_hUBhoB8JZc-BPXEseid5H0Hw',
    appId: '1:93113263271:ios:711ee1047d5e95851aa782',
    messagingSenderId: '93113263271',
    projectId: 'life-way-2003',
    storageBucket: 'life-way-2003.appspot.com',
    iosBundleId: 'com.example.firstly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbIoQFq1_hUBhoB8JZc-BPXEseid5H0Hw',
    appId: '1:93113263271:ios:711ee1047d5e95851aa782',
    messagingSenderId: '93113263271',
    projectId: 'life-way-2003',
    storageBucket: 'life-way-2003.appspot.com',
    iosBundleId: 'com.example.firstly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQH0igY5atcI7OaPbdBsJTUr_egpW5b1Q',
    appId: '1:93113263271:web:5a9974687d0c47d21aa782',
    messagingSenderId: '93113263271',
    projectId: 'life-way-2003',
    authDomain: 'life-way-2003.firebaseapp.com',
    storageBucket: 'life-way-2003.appspot.com',
    measurementId: 'G-6D0ZLCBBK3',
  );
}
